Repository networkx/grave, pull requests merged in 2018-04, with the labels that each got.

#15 Doc refactor
  INSTALL.rst
  LICENSE
  README.md
  doc/Makefile
  doc/api.rst
  doc/conf.py
  doc/developer/index.rst
  doc/developer/notes.rst
  doc/index.rst
  doc/install.rst
  doc/license.rst
  doc/make.bat
  examples/plot_dominators.py
  examples/plot_jarrod_graphxd.py
  examples/plot_layout.py
  examples/plot_layout_custom.py
  examples/plot_use_attributes_centrality.py
  examples/sprint_notes.py
  examples/sprint_notes2.py
  examples/style_attr.py
  grave/tests/test_grave.py
  setup.py
Labels: documentation

#18 Add Appveyor CI
  .appveyor.yml
  setup.py
Labels: enhancement

#19 Improve README
  README.md
  README.rst
  doc/_static/default.svg
  doc/_static/dominators.svg
  doc/default.png
  doc/dominators.png
Labels: documentation

#20 Nb2plots
  doc/_static/copybutton.js
  doc/api.rst
  doc/conf.py
  doc/index.rst
  examples/plot_basics.py
  requirements/doc.txt
Labels: documentation

#21 Deploy latest docs to GH pages via TravisCI
  .travis.yml
  doc/conf.py
  tools/travis/deploy-key.enc
  tools/travis/deploy_docs.sh
  tools/travis/osx_install.sh
  tools/travis/script.sh
Labels: documentation

#22 Release notes
  INSTALL.rst
  README.rst
  doc/conf.py
  doc/developer/index.rst
  doc/developer/release.rst
  doc/index.rst
  doc/release/contribs.py
  doc/release/index.rst
  doc/release/release_dev.rst
  doc/release/release_template.rst
Labels: documentation

#24 plot_network fails if there is no edges to plot.
  Makefile
  examples/plot_layout_custom.py
  grave/_layout.py
  grave/grave.py
  grave/tests/test_grave.py
Labels: bug
